<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ToyLims.StandardClient</AssemblyName>
    <RootNamespace>ToyLims.StandardClient</RootNamespace>
    <ApplicationIcon>..\..\image\toy-lims-client.ico</ApplicationIcon>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SharpVectors.Wpf" Version="1.8.5" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="..\..\image\toy-lims.svg" Link="Resources\toy-lims.svg" />
    <Content Include="standard-client.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
