import json
import os
import sqlite3
import tempfile
import unittest
from unittest import mock

import db_backend
from db_backend import CompatRow, _postgres_sql, postgres_schema
from db_schema import SCHEMA, initialize_database


class DatabaseBackendTest(unittest.TestCase):
    def test_postgres_sql_converts_parameters_without_touching_literals(self):
        converted = _postgres_sql("SELECT '?' AS literal FROM samples WHERE id=?")
        self.assertIn("SELECT '?' AS literal", converted)
        self.assertIn("id=%s", converted)

    def test_postgres_insert_ignore_returns_identity(self):
        converted = _postgres_sql("INSERT OR IGNORE INTO analytes(name) VALUES(?)")
        self.assertIn("INSERT INTO analytes", converted)
        self.assertIn("ON CONFLICT DO NOTHING", converted)
        self.assertTrue(converted.endswith("RETURNING id"))

    def test_postgres_schema_orders_dependencies_and_converts_sqlite_ddl(self):
        source = """
        CREATE TABLE IF NOT EXISTS samples(
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            special_method_id INTEGER REFERENCES special_methods(id),
            created_at TEXT DEFAULT (datetime('now','localtime')));
        CREATE TABLE IF NOT EXISTS special_methods(
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            value REAL);
        """
        converted = postgres_schema(source)
        self.assertLess(converted.index("special_methods("), converted.index("samples("))
        self.assertNotIn("AUTOINCREMENT", converted)
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", converted)
        self.assertIn("DOUBLE PRECISION", converted)
        self.assertNotIn("datetime('now'", converted)

    def test_compat_row_supports_mapping_and_position(self):
        row = CompatRow(("id", "name"), (15, "RY28888"))
        self.assertEqual(15, row[0])
        self.assertEqual("RY28888", row["name"])
        self.assertEqual({"id": 15, "name": "RY28888"}, dict(row))

    def test_canonical_postgres_schema_allows_personal_terminals(self):
        converted = postgres_schema(SCHEMA)
        self.assertIn("CHECK(kind IN ('standard','admin','personal'))", converted)
        self.assertIn("CREATE TABLE IF NOT EXISTS chemical_elements", converted)
        self.assertIn("CREATE TABLE IF NOT EXISTS common_oxides", converted)

    def test_chemical_element_reference_data_is_complete_and_idempotent(self):
        with tempfile.TemporaryDirectory() as directory:
            database = os.path.join(directory, "elements.db")
            initialize_database(database)
            db = sqlite3.connect(database)
            try:
                self.assertEqual(87, db.execute("SELECT COUNT(*) FROM chemical_elements").fetchone()[0])
                self.assertEqual((26, "Fe", "铁", 55.845, 0), db.execute(
                    "SELECT atomic_number,symbol,name_zh,atomic_weight,is_mass_number "
                    "FROM chemical_elements WHERE symbol='Fe'").fetchone())
                self.assertEqual({("Tc", 98.0), ("Pm", 145.0), ("Pu", 244.0), ("Am", 243.0)}, set(db.execute(
                    "SELECT symbol,atomic_weight FROM chemical_elements WHERE is_mass_number=1")))
                self.assertEqual(("Bi", "铋", 208.98), db.execute(
                    "SELECT symbol,name_zh,atomic_weight FROM chemical_elements "
                    "WHERE atomic_number=83").fetchone())
                self.assertEqual(79, db.execute("SELECT COUNT(*) FROM common_oxides").fetchone()[0])
                ferric = db.execute("""SELECT name_zh,element_count,oxygen_count,
                    molar_mass,element_mass_fraction,element_to_oxide_factor,is_conventional
                    FROM common_oxides WHERE formula='Fe2O3'""").fetchone()
                self.assertEqual(("三氧化二铁", 2, 3), ferric[:3])
                self.assertAlmostEqual(159.687, ferric[3], places=6)
                self.assertAlmostEqual(1.4297340854, ferric[5], places=9)
                self.assertAlmostEqual(1.0, ferric[4] * ferric[5], places=12)
                self.assertEqual(1, ferric[6])
                self.assertEqual({"FeO", "Fe2O3", "Fe3O4"}, {row[0] for row in db.execute(
                    "SELECT formula FROM common_oxides WHERE element_symbol='Fe'")})
                mercury = db.execute("""SELECT element_symbol,element_count,oxygen_count,
                    element_to_oxide_factor,is_conventional FROM common_oxides
                    WHERE formula='HgO'""").fetchone()
                self.assertEqual(("Hg", 1, 1), mercury[:3])
                self.assertAlmostEqual(1.0797597089, mercury[3], places=9)
                self.assertEqual(1, mercury[4])
                db.execute("UPDATE chemical_elements SET atomic_weight=999 WHERE symbol='Fe'")
                db.execute("UPDATE common_oxides SET element_to_oxide_factor=999 WHERE formula='Fe2O3'")
                db.commit()
            finally:
                db.close()
            initialize_database(database)
            db = sqlite3.connect(database)
            try:
                self.assertEqual(55.845, db.execute(
                    "SELECT atomic_weight FROM chemical_elements WHERE symbol='Fe'").fetchone()[0])
                self.assertAlmostEqual(1.4297340854, db.execute(
                    "SELECT element_to_oxide_factor FROM common_oxides "
                    "WHERE formula='Fe2O3'").fetchone()[0], places=9)
            finally:
                db.close()

    def test_existing_sqlite_terminal_constraint_is_upgraded(self):
        with tempfile.TemporaryDirectory() as directory:
            database = os.path.join(directory, "legacy.db")
            db = sqlite3.connect(database)
            db.executescript("""CREATE TABLE terminals(
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT UNIQUE NOT NULL,
                password_hash TEXT NOT NULL,
                kind TEXT NOT NULL CHECK(kind IN ('standard','admin')),
                active INTEGER DEFAULT 1,
                sort_order INTEGER NOT NULL DEFAULT 0,
                created_at TEXT DEFAULT (datetime('now','localtime')),
                updated_at TEXT DEFAULT (datetime('now','localtime')));
                INSERT INTO terminals(name,password_hash,kind,sort_order)
                VALUES('旧终端','hash','standard',1);""")
            db.commit()
            db.close()

            initialize_database(database)
            db = sqlite3.connect(database)
            try:
                schema = db.execute("SELECT sql FROM sqlite_master WHERE name='terminals'").fetchone()[0]
                self.assertIn("personal", schema)
                db.execute("INSERT INTO terminals(name,password_hash,kind,sort_order) "
                           "VALUES('个人终端','hash','personal',2)")
                self.assertEqual("旧终端", db.execute(
                    "SELECT name FROM terminals WHERE id=1").fetchone()[0])
            finally:
                db.close()

    def test_legacy_reported_status_and_permission_are_migrated(self):
        with tempfile.TemporaryDirectory() as directory:
            database = os.path.join(directory, "legacy-review.db")
            initialize_database(database)
            db = sqlite3.connect(database)
            try:
                db.execute("INSERT INTO samples(name,status,status_action,reviewer) VALUES(?,?,?,?)",
                           ("旧报告样品", "reported", "reported", "旧审核员"))
                db.execute("""INSERT INTO users(username,password_hash,display_name,role,permissions)
                    VALUES('legacy','hash','旧管理员','admin',?)""",
                           (json.dumps(["report_override", "review_release"]),))
                db.commit()
            finally:
                db.close()
            initialize_database(database)
            db = sqlite3.connect(database)
            try:
                self.assertEqual(("reviewed", "reviewed", "旧审核员"), db.execute(
                    "SELECT status,status_action,reviewer FROM samples WHERE name='旧报告样品'").fetchone())
                permissions = json.loads(db.execute(
                    "SELECT permissions FROM users WHERE username='legacy'").fetchone()[0])
                self.assertIn("result_override", permissions)
                self.assertNotIn("report_override", permissions)
            finally:
                db.close()
    def test_postgres_connection_sets_local_time_zone(self):
        fake_raw = mock.MagicMock()
        with mock.patch.object(db_backend, "psycopg") as fake_psycopg:
            fake_psycopg.connect.return_value = fake_raw
            db_backend.PostgresConnection("postgresql://example")
        fake_raw.execute.assert_called_once_with("SET TIME ZONE 'Asia/Shanghai'")

    def test_postgres_execute_does_not_parse_percent_without_parameters(self):
        fake_raw = mock.MagicMock()
        cursor = mock.MagicMock(description=None, rowcount=0)
        with mock.patch.object(db_backend, "psycopg") as fake_psycopg:
            fake_psycopg.connect.return_value = fake_raw
            fake_raw.execute.return_value = cursor
            connection = db_backend.PostgresConnection("postgresql://example")
            fake_raw.execute.reset_mock()
            connection.execute("ALTER TABLE methods ADD output_unit TEXT DEFAULT '%'")
        fake_raw.execute.assert_called_once_with(
            "ALTER TABLE methods ADD output_unit TEXT DEFAULT '%'")

    def test_approved_formula_catalog_is_seeded_once(self):
        with tempfile.TemporaryDirectory() as directory:
            database = os.path.join(directory, "fresh.db")
            initialize_database(database)
            db = sqlite3.connect(database)
            db.row_factory = sqlite3.Row
            try:
                rows = list(db.execute("""SELECT name,formula,output_unit,active
                    FROM methods WHERE itype='function' ORDER BY sort_order,id"""))
                self.assertEqual(27, len(rows))
                self.assertTrue(all(row["active"] == 1 for row in rows))
                self.assertEqual("Cu-碘量法", rows[0]["name"])
                self.assertEqual("TN-总氮浓度计算", rows[-1]["name"])
                self.assertEqual("ppm", next(row["output_unit"] for row in rows
                                              if row["name"] == "COD-重铬酸钾法"))
                self.assertEqual("mol/L", next(row["output_unit"] for row in rows
                                                if row["name"] == "H+-酸碱滴定法"))
                for row in rows:
                    import app as lims
                    lims.formula_variables(row["formula"])
            finally:
                db.close()
            initialize_database(database)
            db = sqlite3.connect(database)
            try:
                self.assertEqual(27, db.execute(
                    "SELECT COUNT(*) FROM methods WHERE itype='function'").fetchone()[0])
                self.assertEqual(1, db.execute(
                    "SELECT COUNT(*) FROM method_catalog_migrations").fetchone()[0])
            finally:
                db.close()

    def test_existing_formula_methods_are_disabled_during_catalog_upgrade(self):
        with tempfile.TemporaryDirectory() as directory:
            database = os.path.join(directory, "legacy-methods.db")
            initialize_database(database)
            db = sqlite3.connect(database)
            db.execute("DELETE FROM method_catalog_migrations")
            db.execute("INSERT INTO methods(name,itype,formula,active) VALUES('旧方法','function','V',1)")
            legacy_id = db.execute("SELECT id FROM methods WHERE name='旧方法'").fetchone()[0]
            db.commit()
            db.close()
            initialize_database(database)
            db = sqlite3.connect(database)
            try:
                self.assertEqual(0, db.execute(
                    "SELECT active FROM methods WHERE id=?", (legacy_id,)).fetchone()[0])
                self.assertEqual(27, db.execute(
                    "SELECT COUNT(*) FROM methods WHERE itype='function' AND active=1").fetchone()[0])
            finally:
                db.close()


if __name__ == "__main__":
    unittest.main()
